WebApplication2/WebApplication2/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class Product
    {
        public int Id { get; set; }
        public ICollection<CartItem> CartItems { get; set; }
        public string? Title { get; set; }
        [DataType(DataType.Time)]
        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }
        public string? Genre { get; set; }
        public decimal Price { get; set; }
        [Display(Name = "Image")]
        public string? imagePath { get; set; }
        [NotMapped]
        public IFormFile? imageFile { get; set; }

        public Product() { }
        public Product(string nvtitle)
        {
            Title = nvtitle;
        }

        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType()) return false;
            Product product = (Product)obj;
            if (this.Id == product.Id) return true;
            return false;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}

WebApplication2/WebApplication2/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly WebApplication2Context _context;

        public CartItemsController(WebApplication2Context context)
        {
            _context = context;
        }

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var webApplication2Context = _context.CartItem.Include(c => c.Cart).Include(c => c.Product);
            return View(await webApplication2Context.ToListAsync());
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CartItem == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.Cart)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["Cart_Id"] = new SelectList(_context.Cart, "Id", "Id");
            ViewData["Product_Id"] = new SelectList(_context.Product, "Id", "Id");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Product_Id,Cart_Id")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cart_Id"] = new SelectList(_context.Cart, "Id", "Id", cartItem.Cart_Id);
            ViewData["Product_Id"] = new SelectList(_context.Product, "Id", "Id", cartItem.Product_Id);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CartItem == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["Cart_Id"] = new SelectList(_context.Cart, "Id", "Id", cartItem.Cart_Id);
            ViewData["Product_Id"] = new SelectList(_context.Product, "Id", "Id", cartItem.Product_Id);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Product_Id,Cart_Id")] CartItem cartItem)
        {
            if (id != cartItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cart_Id"] = new SelectList(_context.Cart, "Id", "Id", cartItem.Cart_Id);
            ViewData["Product_Id"] = new SelectList(_context.Product, "Id", "Id", cartItem.Product_Id);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CartItem == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItem
                .Include(c => c.Cart)
                .Include(c => c.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CartItem == null)
            {
                return Problem("Entity set 'WebApplication2Context.CartItem'  is null.");
            }
            var cartItem = await _context.CartItem.FindAsync(id);
            if (cartItem != null)
            {
                _context.CartItem.Remove(cartItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartItemExists(int id)
        {
          return (_context.CartItem?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/WebApplication2/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using WebApplication2.Data;
using WebApplication2.Models;
using WebApplication2.Services;

namespace WebApplication2.Controllers
{
    public class ProductsController : Controller
    {
        private readonly WebApplication2Context _context;
        private readonly IMemoryCache _memoryCache;
        private readonly ILoggerFactory _loggerFactory;

        public ProductsController(WebApplication2Context context, IMemoryCache memoryCache, ILoggerFactory loggerFactory)
        {
            _context = context;
            _memoryCache = memoryCache;
            _loggerFactory = loggerFactory;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchString)
        {

            //if (_context.Product == null)
            //{
            //    return Problem("Entity set 'WebApplication2Context.Product'  is null.");
            //}
            //var products = from p in _context.Product select p;
            //if (!String.IsNullOrEmpty(searchString) && Security.Security.IsValidInput_SQLInjection(searchString))
            //{
            //    products = products.Where(s => s.Title!.Contains(searchString));
            //}
            //return View(await products.ToListAsync());
            // Create a cache key based on the method name and the input parameters
            string cacheKey = $"GetProducts_{searchString}";

            // Try to get the result from the cache
            if (_memoryCache.TryGetValue(cacheKey, out List<Product> cachedProducts))
            {
                // Use the cached result
                return View(cachedProducts);
            }

            // If not in the cache, perform the database query
            if (_context.Product == null)
            {
                return Problem("Entity set 'WebApplication2Context.Product' is null.");
            }

            var products = from p in _context.Product select p;

            if (!String.IsNullOrEmpty(searchString) && Security.Security.IsValidInput_SQLInjection(searchString))
            {
                products = products.Where(s => s.Title!.Contains(searchString));
            }

            // Execute the query and convert to a list
            List<Product> result = await products.ToListAsync();

            // Use _loggerFactory to create an ILogger instance
            ILogger logger = _loggerFactory.CreateLogger<ProductsController>();

            // Now you can use the logger to log messages
            logger.LogInformation("[LOG MESSAGE : CACHE] This is a Logging Message : Products List is cached since it is fetched for the first time !");

            // Store the result in the cache with a specific expiration time (e.g., 10 minutes)
            _memoryCache.Set(cacheKey, result, TimeSpan.FromMinutes(10));

            return View(result);
    }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // Use _loggerFactory to create an ILogger instance
            ILogger logger = _loggerFactory.CreateLogger<ProductsController>();

            // Now you can use the logger to log messages
            logger.LogInformation("This is a Logging Message : Method Details Controller : Products");
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            // Use _loggerFactory to create an ILogger instance
            ILogger logger = _loggerFactory.CreateLogger<ProductsController>();

            // Now you can use the logger to log messages
            logger.LogInformation("This is a Logging Message : Method Create Controller : Products");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Price")] Product product, IFormFile imageFile)
        {
            // Use _loggerFactory to create an ILogger instance
            ILogger logger = _loggerFactory.CreateLogger<ProductsController>();

            // Now you can use the logger to log messages
            logger.LogInformation("This is a Logging Message : Method Create Controller : Products");
            if (imageFile != null && imageFile.Length > 0)
                {
                    var fileName = Path.GetRandomFileName() + Path.GetExtension(imageFile.FileName);

                    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
                    var filePath = Path.Combine(uploadsFolder, fileName);

                    Directory.CreateDirectory(uploadsFolder);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);
                    }

                    // Save the file path in your database
                    product.imagePath = "/images/" + fileName; // Update the path as per your project structure
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price,imagePath")] Product product)
        {
            // Use _loggerFactory to create an ILogger instance
            ILogger logger = _loggerFactory.CreateLogger<ProductsController>();

            // Now you can use the logger to log messages
            logger.LogInformation("This is a Logging Message : Method Edit Controller : Products");
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'WebApplication2Context.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/WebApplication2/Views/Products/Create.cshtml
@model WebApplication2.Models.Product

@{
    ViewData["Title"] = "Create";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet" />
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css"
      rel="stylesheet" />
<!-- MDB -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="imagePath" class="control-label"></label>
                <input asp-for="imagePath" class="form-control" />
                <span asp-validation-for="imagePath" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="imageFile" class="control-label">Image</label>
                <input type="file" class="form-control" id="imageFile" name="imageFile" />
                <span asp-validation-for="imageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/WebApplication2/Views/Products/Delete.cshtml
@model WebApplication2.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/WebApplication2/Views/Products/Details.cshtml
@model WebApplication2.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/WebApplication2/Views/Products/Edit.cshtml
@model WebApplication2.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="imagePath" class="control-label"></label>
                <input asp-for="imagePath" class="form-control" />
                <span asp-validation-for="imagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/WebApplication2/Views/Products/Index.cshtml
@model IEnumerable<WebApplication2.Models.Product>

@{
    ViewData["Title"] = "Index";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet" />
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css"
      rel="stylesheet" />
<!-- MDB -->
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>
<style>
    .card:hover{
        transform: scale(1.1);
        transition:transform opacity 0.3s ease-in-out;
        background-image:none !important;
    }

    .card:hover .card-body{
        display:flex !important;
        justify-content: space-around;
    }
    button {
        height: 35px;
    }
</style>

<div class="row d-flex justify-content-end">
    <div class="col-1">
        <a asp-action="Create" class="btn btn-primary">
            <i class="fas fa-square-plus"></i>
        </a>
    </div>
</div>
<div class="container bg-light mt-5">
    <div class="row d-flex justify-content-between">

        @foreach (var item in Model)
        {
            <div class="card col-3" style="background-image:url(@item.imagePath); background-size:cover; background-repeat:no-repeat; background-position-x:center; background-position-y:center;height:120px">
                <div class="card-body mt-3" style="display:none">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success col-2 d-flex align-content-center justify-content-center" style="height:35px">
                        <i class="fas fa-pen"></i>
                    </a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning col-2 d-flex align-content-center justify-content-center" style="height:35px">
                        <i class="fas fa-info"></i>
                     </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger col-2 d-flex align-content-center justify-content-center" style="height:35px">
                        <i class="fas fa-trash"></i>
                     </a>
                    @* <a asp-action="Create" asp-controller="CartItems" asp-route-Product_Id=@item.Id asp-route-Cart_Id="1" class="btn btn-primary col-2 d-flex align-content-center justify-content-center" style="height:35px">
                        <i class="fa-solid fa-cart-plus"></i>
                    </a> *@
                    <form class="col-2" asp-action="Create" asp-controller="CartItems">
                        <input name="Product_Id" type="text" value=@item.Id hidden/>
                        <input name="Cart_Id" type="text" value="1" hidden/>
                        <button type="submit" class="col-2 btn btn-primary d-flex align-content-center justify-content-center">
                            <i class="fa-solid fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        }
    </div>
</div>

</table>